# Generated by Django 4.0.4 on 2022-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('href', models.TextField(default='#')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
