# Generated by Django 4.0.4 on 2022-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_navlinks_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlinks',
            name='name',
            field=models.CharField(max_length=48),
        ),
    ]
